// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Tmp$BsTmp = require("../src/Tmp.js");

describe("Tmp", (function () {
        return Jest.test("system temp file", (function () {
                      var path = Tmp$BsTmp.tempFile(/* None */0, /* None */0, /* () */0);
                      return Jest.Expect[/* toMatchRe */15]((/\/tmp\/tmp-(\w+)\.tmp/), Jest.Expect[/* expect */0](path));
                    }));
      }));

/*  Not a pure module */
