// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Tmp = require("tmp");

function make(dir, prefix, postfix, _) {
  var tmp = {
    discardDescriptor: true
  };
  if (dir) {
    tmp.dir = dir[0];
  }
  if (prefix) {
    tmp.prefix = prefix[0];
  }
  if (postfix) {
    tmp.postfix = postfix[0];
  }
  var params = tmp;
  var tmp$1;
  if (dir) {
    var dir$1 = dir[0];
    var match = Fs.existsSync(dir$1);
    if (!match) {
      Fs.mkdirSync(dir$1);
    }
    tmp$1 = Tmp.dirSync(params);
  } else {
    tmp$1 = Tmp.fileSync(params);
  }
  return tmp$1.name;
}

exports.make = make;
/* fs Not a pure module */
