// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Tmp = require("tmp");

function make(dir, prefix, postfix, _) {
  var tmp = {
    discardDescriptor: true
  };
  if (dir) {
    tmp.dir = dir[0];
  }
  if (prefix) {
    tmp.prefix = prefix[0];
  }
  if (postfix) {
    tmp.postfix = postfix[0];
  }
  var params = tmp;
  return (
          dir ? Tmp.dirSync(params) : Tmp.fileSync(params)
        ).name;
}

exports.make = make;
/* tmp Not a pure module */
